export interface Template {
  id: number;
  title: string;
  category: string;
  theme: string;
  price: number;
  originalPrice: number | null;
  image: string;
  rating: number;
  reviews: number;
  colors: string[];
  ratio: string;
  isNew: boolean;
}

export const templates: Template[] = [
  {
    id: 1,
    title: "Modern Instagram Stories Pack",
    category: "Instagram",
    theme: "Kreativní",
    price: 590,
    originalPrice: 790,
    image: "/templates/instagram-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#3B82F6", "#10B981"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 2,
    title: "Professional LinkedIn Templates",
    category: "LinkedIn",
    theme: "Business",
    price: 890,
    originalPrice: null,
    image: "/templates/linkedin-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#3B82F6", "#8B5CF6"],
    ratio: "1:1",
    isNew: false,
  },
  {
    id: 3,
    title: "Minimalist Instagram Posts",
    category: "Instagram",
    theme: "Minimalistické",
    price: 690,
    originalPrice: 890,
    image: "/templates/instagram-2.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#EF4444", "#F59E0B"],
    ratio: "1:1",
    isNew: false,
  },
  {
    id: 4,
    title: "Pinterest Pin Bundle",
    category: "Pinterest",
    theme: "Kreativní",
    price: 790,
    originalPrice: null,
    image: "/templates/pinterest-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#EC4899", "#8B5CF6"],
    ratio: "4:5",
    isNew: true,
  },
  {
    id: 5,
    title: "Bold Facebook Ads Templates",
    category: "Facebook",
    theme: "Výrazné",
    price: 990,
    originalPrice: 1290,
    image: "/templates/facebook-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#EF4444", "#3B82F6"],
    ratio: "1:1",
    isNew: false,
  },
  {
    id: 6,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 7,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 8,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 9,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 10,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 11,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
  {
    id: 12,
    title: "Elegant Social Media Bundle",
    category: "Instagram",
    theme: "Elegantní",
    price: 1190,
    originalPrice: null,
    image: "/templates/bundle-1.jpg",
    rating: 0,
    reviews: 0,
    colors: ["#8B5CF6", "#EC4899"],
    ratio: "9:16",
    isNew: true,
  },
];
